const keywordMap: Record<string, string> = {
  bedding: '침구류',
  TV: '티비',
  switch: '스마트 불끄기 푸시봇',
  curtain: '커튼',
  stand: '거치대',
  dryer: '건조기',
  shoes_dryer: '신발 건조기',
  dehumidifier: '제습기',
  bath: '욕조',
  cleaning: '에어컨 청소키트, 하수구 트랩',
  organizer: '정리함',
  fan: '선풍기',
  aircon: '에어컨',
  food_waste: '음식물 처리기',
  airflier: '에어 프라이어',
  bug: '벌레퇴치관련',
  pot: '냄비',
  mood_light: '무드등',
  concent: '콘센트커버',
  plug: '스마트 플러그',
  multitab: '멀티탭',
  bed: '소파베드',
  tile: '타일',
  spoon: '국자',
  desk: '책상',
  drawer: '서랍장',
  dryerstand: '빨래건조대',
  cosmetic_fridge: '화장품 냉장고',
  poster: '포스터',
  bim_project: '빔프로젝터',
  hangger: '행거',
  umbrealla_stand: '우산꽂이',
  shoesrack: '슈즈렉',
  shelf: '선반',
  bookcase: '책장',
  partition: '공간분리 파티션',
  plant: '식물',
  bowl: '그릇',
  iron: '다리미',
  night_wear: '잠옷',
  door_sensor: '스마트 알람 도어센서',
  door_stopper: '도어스토퍼',
  table: '식탁',
  candle: '캔들',
  brush: '셀프 등밀이 브러쉬',
  spray: '바디스프레이',
  vacuum: '청소기',
  mirror: '거울',
  coffee_machine: '커피머신',
};
export default keywordMap;
